# Generated by Django 3.0 on 2020-04-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200416_0751'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonChinese',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chinese', models.CharField(max_length=255)),
                ('pinyin', models.CharField(max_length=255)),
                ('vietnamese', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='Word',
            new_name='WordInLesson',
        ),
    ]
