# Generated by Django 3.0 on 2020-04-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200418_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonchinese',
            name='vietnamese',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
