# Generated by Django 3.0 on 2020-04-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200418_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonchinese',
            name='vietnamese',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
